### ISSUE TITLE
Koth point broadcast's in non-koth servers (S08,S02,ect.)

### ISSUE THREAD

**Issue by Yahm1234** [Casimir255/SeamlessClientPlugin#13]
**Describe the bug**
When playing on many different servers (I have seen in 02, 08, and 10 with others reporting it in 14) the KOTH point broadcasts can be seen.  I am not sure if it is a constant issue or intermittent as I can't know when KOTH points are given, but when it is seen it is seen for a couple of hours.

**To Reproduce**
Encountered in general gameplay, seems to occur without any cause by the user

**Expected behavior**
For KOTH points to not be broadcast in non-koth servers

**Screenshots**

**Additional context**
I have resubbed to GitHub for the plugin, with it displaying 1.0, this issue appears to be consistent regardless of any other plugins loaded, as it was noted first with seamless being the only loaded plugin and with others as well. Other users have reported the same issue in general chat infrequently.

**Comment by Yahm1234** [comment]
Screenshot below 
![image](https://user-images.githubusercontent.com/84950314/119936032-20963000-bf4e-11eb-8623-e8dd6c149add.png)

**Comment by Casimir255** [comment]
So, im not sure if I fixed it yet, but I did change a few chat things...

The expected behavior is to see the chat from other servers. That was a nexus change I did a few weeks back to let other mods sync messages across all sectors. BUT, if that didn't work, and you were just in that sector,  then switched out, and are the only one getting it, then that would be an issue.

On the next seamless update, you can let me know if it's been fixed. Ill level the issue open till then. (Hopefully Ill push update in a few days. I had a few other things to fix too)
